openapi: 3.0.0
info:
  title: Combined API
  description: API documentation for Promises, Tasks, Locks, and Schedules.
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://resonatehq.io # Replace with your actual API base URL
    description: Website
security: [] # Explicitly state no security is required globally
paths:
  /promises:
    $ref: "./promises-openapi.yml#/paths"
  /tasks:
    $ref: "./tasks-openapi.yml#/paths"
  /locks:
    $ref: "./locks-openapi.yml#/paths"
  /schedules:
    $ref: "./schedules-openapi.yml#/paths"

components:
  parameters:
    PromiseParameters:
      $ref: "./promises-openapi.yml#/components/parameters"
    ScheduleParameters:
      $ref: "./schedules-openapi.yml#/components/parameters"
  schemas:
    PromiseSchema:
      $ref: "./promises-openapi.yml#/components/schemas"
    ScheduleSchema:
      $ref: "./schedules-openapi.yml#/components/schemas"
    LockSchema:
      $ref: "./locks-openapi.yml#/components/schemas"
    TaskSchema:
      $ref: "./tasks-openapi.yml#/components/schemas"
